version: '3'

services:
  php:
    container_name: laravel_vue_graphql_php
    build: ./docker/php
    volumes:
      - ./backend:/var/www
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: laravel_vue_graphql_nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: laravel_vue_graphql_db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_vue_graphql_admin
    ports:
      - 6565:80
    depends_on:
      - db
    environment:
      PMA_ARBIRTRARY: 1
      PMA_HOST: db:3306
      PMA_USER: root
      PMA_PASSWORD: password
    links:
      - db

